[tool.poetry]
name = "test-pipeline-ops"
version = "0.1.0"
description = "Simple Lambda handler for PipelineOps testing"
authors = ["Khiem Huynh <khiemhuynh952@gmail.com>"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
